services:
  - type: web
    name: product-voting-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/Alok-Kumar27/Product-Voting-App
    branch: main